name: Check minimum supported Rust version (MSRV)

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      checkout_ref:
        description: "Git ref (branch, tag or SHA) to check out"
        required: false
        type: string

env:
  RUST_BACKTRACE: full
  CI: true
  PROFILE: debug

jobs:
  check-msrv:
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ inputs.checkout_ref }}
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-24.04.sh
      - run: bash scripts/environment/prepare.sh --modules=cargo-msrv
      - run: cargo msrv verify
